- api/.env
- api/.gitignore
- api/bin/console
- api/composer.json
- api/composer.lock
- api/config/bundles.php
- api/config/packages/cache.yaml
- api/config/packages/framework.yaml
- api/config/packages/routing.yaml
- api/config/preload.php
- api/config/routes.yaml
- api/config/routes/framework.yaml
- api/config/services.yaml
- api/public/index.php
- api/src/Kernel.php
- api/symfony.lock
> 5 install symfony

- api/migrations/Version20220911194023.php
- api/src/Entity/Question.php
- api/src/Entity/Quiz.php
- api/src/Repository/QuestionRepository.php
> 8 question entity

- api/migrations/Version20220911194911.php
- api/src/Entity/Answer.php
- api/src/Entity/Question.php
- api/src/Repository/AnswerRepository.php
> [9] Adding question entity, repository and migration

- api-client/package.json
> [24] Creating the api-client

- CONTRIBUTING.md
- Adds the contribution guide
...
> [32] Fixes #32 Adding contribution guide

- api-client/api-models.ts
- api-client/mockData/htmlAnswers.ts
- api-client/mockData/htmlQuestions.ts
- api-client/mockData/quiz.ts
> [38] Added two HTML questions and answers to the API Fixes #38

- README.md
- As per title, this PR resolves #37 and involves only a few line changes in [README.md](README.md)
My editor settings took care of removing trailing whitespaces, hope you won't mind.
As per the checklist, no real code is involved in this PR, hence left them empty, do let me know if you prefer the checklist completed for the sake of consistency with other PRs.
>  [37] Fixes #37 Add link to contribution guidelines in README

- README.md
> [42] Fixes #42 Adding System requirements

- README.md
- api/composer.json
- api/composer.lock
- api/config/bundles.php
- api/config/fixtures/quizzes/html-quiz/questions/question_1.php
- api/config/fixtures/quizzes/html-quiz/questions/question_2.php
- api/config/fixtures/quizzes/html-quiz/quiz.php
- api/src/DataFixtures/AppFixtures.php
- api/src/Entity/Question.php
- api/src/Entity/Quiz.php
- api/symfony.lock
> [45] fixtures

- api/.gitignore
- api/composer.json
- api/composer.lock
- api/phpstan.neon.dist
> [46] Adding phpstan

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> 51 contribution rules

- .github/workflows/api.yml
> 53 GitHub action

- .github/workflows/api.yml
- api/src/DataFixtures/AppFixtures.php
> 55 breaking code to test PHPStan pipeline

- api-client/mockData/htmlAnswers.ts
> remove 't' from question 2

- .github/workflows/api.yml
- api/.gitignore
- api/composer.json
- api/composer.lock
- api/phpcs.xml.dist
- api/src/DataFixtures/AppFixtures.php
- api/src/Repository/AnswerRepository.php
- api/src/Repository/QuestionRepository.php
- api/src/Repository/QuizRepository.php
- api/symfony.lock
> 61 install phpcs

- README.md
> #75 Updating readme

- .github/workflows/api.yaml
- api/.dockerignore
- api/.env.test
- api/.gitignore
- api/Dockerfile
- api/bin/phpunit
- api/composer.json
- api/composer.lock
- api/docker-compose.override-sample.yml
- api/docker-compose.test.yml
- api/docker-compose.yml
- api/infra/api/error_reporting.ini
- api/infra/api/xdebug.ini
- api/phpunit.xml.dist
- api/symfony.lock
- api/tests/bootstrap.php
> 81 install php unit

- .github/workflows/api.yaml
- api/phpunit.xml.dist
- api/tests/unit/Entity/AnswerTest.php
- api/tests/unit/Entity/QuestionTest.php
- api/tests/unit/Entity/QuizTest.php
> #83 Adding entity tests

- api/phpunit.xml.dist
> #91 Excluding src/kernel.php from PHPUnit code coverage"

- api-client/package.json
- api-client/yarn.lock
> #65 installing axios

- api-client/src/api/apiClient.ts
- api-client/tests/unit/api/apiClient.test.ts
> #98 Adding API client

- api-client/src/api/apiClient.ts
- api-client/src/api/mockClient.ts
- api-client/src/api/requestHandlers/quizRequest.ts
- api-client/src/server.ts
- api-client/tests/unit/integration/api/requestHandlers/quizRequest.test.ts
- Fixes #99 
- Fixes #118 
...
> #99 WIP adding integration tests

- api-client/src/mockData/pythonQuiz/pythonAnswers.ts
- api-client/src/mockData/pythonQuiz/pythonQuestions.ts
- api-client/src/mockData/pythonQuiz/pythonQuiz.ts
- api-client/src/mockData/quiz.ts
- api-client/tests/integration/api/requestHandlers/quizRequest.test.ts
- api/config/fixtures/quizzes/python-quiz/questions/question_1.php
- api/config/fixtures/quizzes/python-quiz/questions/question_2.php
- api/config/fixtures/quizzes/python-quiz/questions/question_3.php
- api/config/fixtures/quizzes/python-quiz/questions/question_4.php
- api/config/fixtures/quizzes/python-quiz/questions/question_5.php
- api/config/fixtures/quizzes/python-quiz/quiz.php
- api/src/DataFixtures/AppFixtures.php
- api/tests/unit/config/fixtures/quizzes/python_quiz/PythonQuizTest.php
- api/tests/unit/config/fixtures/quizzes/python_quiz/questions/PythonQuestionsTest.php
> #80 Adding Python quiz

- api-client/src/mockData/javaScriptQuiz/javaScriptAnswers.ts
- api/config/fixtures/quizzes/javascript-quiz/questions/question_5.php
> #137 Fix answer
